/*
 * OpenFIGI API
 *
 * A free & open API for FIGI discovery.
 *
 * API version: 1.3.0
 * Contact: support@openfigi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openfigi

// For V2: securityType2 is required when idType is BASE_TICKER or ID_EXCH_SYMBOL.  expiration is required when securityType2 is Option or Warrant.  maturity is required when securityType2 is Pool.
type MappingJob struct {
	IdType string `json:"idType"`
	IdValue OneOfstringinteger `json:"idValue"`
	ExchCode *string `json:"exchCode,omitempty"`
	MicCode *string `json:"micCode,omitempty"`
	Currency *string `json:"currency,omitempty"`
	MarketSecDes *string `json:"marketSecDes,omitempty"`
	SecurityType *string `json:"securityType,omitempty"`
	SecurityType2 *string `json:"securityType2,omitempty"`
	IncludeUnlistedEquities *bool `json:"includeUnlistedEquities,omitempty"`
	OptionType *string `json:"optionType,omitempty"`
	// At least one entry should be non-null.
	Strike *[]float32 `json:"strike,omitempty"`
	// At least one entry should be non-null.
	ContractSize *[]float32 `json:"contractSize,omitempty"`
	// At least one entry should be non-null.
	Coupon *[]float32 `json:"coupon,omitempty"`
	// At least one entry should be non-null.
	Expiration *[]string `json:"expiration,omitempty"`
	// At least one entry should be non-null.
	Maturity *[]string `json:"maturity,omitempty"`
}
